name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: pappdanie1
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker images
      run: |
        docker build -t pappdanie1/test:latest -f SolarWatch/Dockerfile .
        docker build -t pappdanie1/test:latest -f client/Dockerfile .
        docker-compose -f /docker-compose.yml up -d
        docker push pappdanie1/test:latest
        docker push pappdanie1/test:latest
