# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      JWSETTINGS__VALIDISSUER: ${{ secrets.JWSETTINGS__VALIDISSUER }}
      JWSETTINGS__VALIDAUDIENCE: ${{ secrets.JWSETTINGS__VALIDAUDIENCE }}
      SIGNINGKEY__ISSUERSIGNINGKEY: ${{ secrets.SIGNINGKEY__ISSUERSIGNINGKEY }}
      DEFAULTCONNECTION: ${{ secrets.DEFAULTCONNECTION }}
      ROLES__1: ${{ secrets.ROLES__1 }}
      ROLES__2: ${{ secrets.ROLES__2 }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./TestSolarWatch
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./TestSolarWatch
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./TestSolarWatch
    - name: Restore dependencies IntegrationTests
      run: dotnet restore
      working-directory: ./IntegrationTest
    - name: Build IntegrationTests
      run: dotnet build --no-restore
      working-directory: ./IntegrationTest
    - name: IntegrationTests
      run: dotnet test --no-build --verbosity normal
      working-directory: ./IntegrationTest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: pappdanie1
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
